version: '3.1'

services:
  nginx:
    container_name: ${NGINX_NAME}
    image: nginx:latest
    volumes:
      - ${PROJECT_PATH}/${NGINX_CONFD}:/etc/nginx/conf.d
      ## You can mount the SSL certificate file into a container.
      ## Copy and customize ./nginx/conf.d/ssl.conf.example.
      #- ${PROJECT_PATH}/${NGINX_CERTS}:/etc/nginx/certs
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    networks:
      - backend
  dp:
    container_name: ${DP_NAME}
    image: dravenk/dp:web
    networks:
      - backend
    ## It can be forwarded to this container by Nginx, 
    ## so the container's exposed port is not required
    #ports:
    #  - "${DP_PORT}:80"
    ## If dp project not exit, please create a project into web folder.
    ## `composer create-project drupal/recommended-project dp "^9.0" -vvv`
    ## You can mount your project in the /var/www/html directory if you need.
    #volumes:
    #  - ./web/dp:/var/www/html

####### mariadb #######
  mariadb:
    image: mariadb:latest
    container_name: ${MARIADB_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    volumes:
      - ${PROJECT_PATH}/${MARIADB_PATH}/data:/var/lib/mysql
    networks:
      - backend

####### adminer #######
## A simple database management web app.
  adminer:
    image: adminer:latest
    container_name: ${ADMINER_NAME}
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - backend

networks:
  backend:
