version: '3.1'

services:
  myapp:
    container_name: ${APP_NAME}
    image: dravenk/dp:latest
    networks:
      - backend
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${PROJECT_PATH}/${WEB_PATH}/app:/var/www/html

networks:
  backend:
    external:
      name: docker-app_backend
